app = "your-app-name"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/"
