app = "your-app-name-here"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  # Thêm các biến môi trường khác tại đây

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

# Cấu hình volume nếu cần lưu trữ file
# [[mounts]]
#   destination = "/var/www/html/storage/app/public"
#   source = "laravel_storage"

# Cấu hình health check
[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  method = "get"
  path = "/"
